### ISSUE TITLE
mkvmerge error after writing file

### ISSUE THREAD

**Issue by LightArrowsEXE** [Ichunjo/vardautomation#106]
https://discord.com/channels/@me/599711298275770398/972537849524154378

Some unknown error can occur when running mkvmerge that can't be caught in a try/except clause. The final output is still being muxed, but it seems to throw an error when trying to exit, taking the entire process down with it.

Removing `check=True` in `tooling/base.py:44` as done here seems to resolve the error
```diff
-            subprocess.run(self.params, check=True, text=True, encoding='utf-8')
+            subprocess.run(self.params, text=True, encoding='utf-8')
```

This might be a temporary solution for the time being, but a more permanent solution should be found asap.

**Comment by LightArrowsEXE** [comment]
> Can you test with this snippet?

Runs without issue.

**Comment by begna112** [comment]
I've had the same issue. 

```
encoded 34046 frames, 2.34 fps, 2011.94 kb/s
Resumable encode; merging...
mkvmerge command: mkvmerge -o L:\encode\Utawarerumono - Futari no Hakuoro\utaware_01_part_000.mkv --quiet L:\encode\Utawarerumono - Futari no Hakuoro\utaware_01_part_000
mkvextract command: mkvextract L:\encode\Utawarerumono - Futari no Hakuoro\utaware_01_tmp.mkv tracks 0:L:\encode\Utawarerumono - Futari no Hakuoro\utaware_01
Extracting track 0 with the CodecID 'V_MPEG4/ISO/AVC' to the file 'L:\encode\Utawarerumono - Futari no Hakuoro\utaware_01'. Container format: AVC/H.264 elementary stream
Progress: 100%
mkvmerge command: mkvmerge -o L:\encode\Utawarerumono - Futari no Hakuoro\Premux\utaware_01 (Premux).mkv --ui-language en --language 0:jpn L:\encode\Utawarerumono - Futari no Hakuoro\utaware_01 --language 1:jpn --track-name 1:AAC 2.0 --tags 0:_settings/tags_aac.xml L:\encode\Utawarerumono - Futari no Hakuoro\utaware_01_2_cut.aac
mkvmerge v65.0.0 ('Too Much') 64-bit
'L:\encode\Utawarerumono - Futari no Hakuoro\utaware_01': Using the demultiplexer for the format 'AVC/H.264'.
'L:\encode\Utawarerumono - Futari no Hakuoro\utaware_01_2_cut.aac': Using the demultiplexer for the format 'AAC'.
'L:\encode\Utawarerumono - Futari no Hakuoro\utaware_01' track 0: Using the output module for the format 'AVC/H.264 (unframed)'.
'L:\encode\Utawarerumono - Futari no Hakuoro\utaware_01_2_cut.aac' track 0: Using the output module for the format 'AAC'.
Warning: 'L:\encode\Utawarerumono - Futari no Hakuoro\utaware_01_2_cut.aac': A track with the ID 1 was requested but not found in the file. The corresponding option will be ignored.
The file 'L:\encode\Utawarerumono - Futari no Hakuoro\Premux\utaware_01 (Premux).mkv' has been opened for writing.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 1 second.
An error has been caught in function '_do_tooling', process 'MainProcess' (3956), thread 'MainThread' (22696):
Traceback (most recent call last):
  File "L:\encode\Utawarerumono - Futari no Hakuoro\utaware_01.py", line 86, in <module>
    runner.run()
  File "C:\Python310\lib\site-packages\vsencode\encoder.py", line 135, in run
    runner.run()
  File "C:\Python310\lib\site-packages\vardautomation\automation.py", line 157, in run
    f()
  File "C:\Python310\lib\site-packages\vardautomation\automation.py", line 251, in _mux
    wf = self.config.mkv.mux(True)
  File "C:\Python310\lib\site-packages\vardautomation\tooling\mux.py", line 326, in mux
    BasicTool(BinaryPath.mkvmerge, self.command).run()
  File "C:\Python310\lib\site-packages\vardautomation\tooling\base.py", line 35, in run
    self._do_tooling()
> File "C:\Python310\lib\site-packages\vardautomation\tooling\base.py", line 45, in _do_tooling
    subprocess.run(self.params, check=True, text=True, encoding='utf-8')
  File "C:\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mkvmerge', '-o', 'L:\\encode\\Utawarerumono - Futari no Hakuoro\\Premux\\utaware_01 (Premux).mkv', '--ui-language', 'en', '--language', '0:jpn', 'L:\\encode\\Utawarerumono - Futari no Hakuoro\\utaware_01', '--language', '1:jpn', '--track-name', '1:AAC 2.0', '--tags', '0:_settings/tags_aac.xml', 'L:\\encode\\Utawarerumono - Futari no Hakuoro\\utaware_01_2_cut.aac']' returned non-zero exit status 1.
```

**Comment by Ichunjo** [comment]
The warning is raised by mkvmerge because a `tid` was specified in the Track constructor. Since `utaware_01_2_cut.aac` isn't a matroska file it doesn't have a TID. Easy fix is to just not specify the TID. The list order of the track is enough to keep the same order in the final mkv file
